@URL=http://localhost:8090
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWExOTEyOGUxYmIwZjBjZDVjNDQ5OCIsInVzZXJOYW1lIjoicXdlIiwidXNlckVtYWlsIjoicXdlcXdlQHFxLmNvbSIsImlkZW50aXR5IjoiZW1wbG95ZWUiLCJpYXQiOjE2Mzc2NDgzOTEsImV4cCI6MTYzNzY0ODQwMX0.pCoUOgM_pngYc2UQu1TyF6LO8oaibLauCZ1W2O1tia8"

###
GET {{URL}}/api/users

###
POST {{URL}}/api/users/register
Content-Type: application/x-www-form-urlencoded

email=123qweasd@qq.com
&name=llb
&password=llb


###
POST {{URL}}/api/users/register
Content-Type: application/x-www-form-urlencoded

email=qweasdzxc@163.com
&name=llb
&password=llb
&identity=gm

###

POST {{URL}}/api/users/login
Content-Type: application/json

{
    "email":"123qweasd@qq.com",
    "name":"llb",
    "password":"llb"
}

###
POST {{URL}}/api/users/login
Content-Type: application/json

{
    "userEmail":"qweqwe@qq.com",
    "userPassword":"qweqwe"
}

###
GET {{URL}}/api/users/profile
Authorization: {{token}}


